-- MySQL Script generated by MySQL Workbench
-- Wed 06 May 2020 04:04:07 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flic_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flic_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flic_service` DEFAULT CHARACTER SET utf8 ;
USE `flic_service` ;

-- -----------------------------------------------------
-- Table `flic_service`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flic_service`.`user_type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(45) NULL DEFAULT 'customer',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flic_service`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flic_service`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL,
  `domain` VARCHAR(100) NULL,
  `key` VARCHAR(100) NULL,
  `user_type_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_user_type_idx` (`user_type_id` ASC),
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `flic_service`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
